### ISSUE TITLE
Incorrect error message

### ISSUE THREAD

**Issue by joaopfonseca** [georgedouzas/imbalanced-learn-extra#11]
When `k_neighbors`>`n_samples` the error message displayed refers to an inexistent hyperparameter `n_neighbors`:

```ValueError: Expected n_neighbors <= n_samples,  but n_samples = 2, n_neighbors = 6```

**Comment by georgedouzas** [comment]
The traceback of the error shows that is raised by the `kneighbors` method of the `KNeighborsMixin` class. So it refers to the name of one of its parameters (`n_neighbors`).
