### ISSUE TITLE
MNIST example

### ISSUE THREAD

**Issue by georgedouzas** [georgedouzas/imbalanced-learn-extra#20]
Example seems broken.

**Comment by joaopfonseca** [comment]
Just opened a PR to fix this. The covtype example is still broken though. I suggest we remove it, it takes very long to download the toy datasets.

**Comment by georgedouzas** [comment]
The add applications examples seem to work locally but not on readthedocs: "Build exited due to excessive memory consumption". @joaopfonseca  can we simplify them to make them built?
