### ISSUE TITLE
TypeError: 'str' object is not callable

### ISSUE THREAD

**Issue by AkinaMH** [georgedouzas/imbalanced-learn-extra#38]
### Describe the bug

X_res, y_res = gsomo.fit_resample(X, y) 

The above code execution will report an error and cannot synthesise a minority class sample.

### Steps or code to reproduce the bug

import numpy as np
from imblearn_extra.clover.over_sampling import GeometricSOMO
from sklearn.datasets import make_blobs
blobs = [100, 800, 100]
X, y  = make_blobs(blobs, centers=[(-10, 0), (0, 0), (10, 0)])
X = np.concatenate([X, [[0, 0]]])
y = np.append(y, 0)
y = y == 1
gsomo = GeometricSOMO(random_state=42)
X_res, y_res = gsomo.fit_resample(X, y)
right, left = X_res[:, 0] > -5, X_res[:, 0] < 5
n_res_in_middle = (right & left).sum()
print("Samples in the middle blob: %s" % n_res_in_middle)
unchanged = n_res_in_middle == blobs[1] + 1
print("Middle blob unchanged: %s" % unchanged)
more_zero_samples = (y_res == 0).sum() > (y == 0).sum()
print("More 0 samples: %s" % more_zero_samples)

### Expected Results

X_res, y_res = gsomo.fit_resample(X, y) 

I would expect the above code to run properly out of x_res and y_res.

### Actual Results

Traceback (most recent call last):
  File "E:\PyCharm\SNNDPC-SMOTE\Test.py", line 26, in <module>
    X_res, y_res = gsomo.fit_resample(X, y)
  File "C:\Users\MH\.conda\envs\py310\lib\site-packages\imblearn_extra\clover\over_sampling\_cluster.py", line 418, in fit_resample
    self._check(X, y)._fit(X, y, **fit_params)
  File "C:\Users\MH\.conda\envs\py310\lib\site-packages\imblearn_extra\clover\over_sampling\_cluster.py", line 509, in _fit
    self.clusterer_.fit(X, y, **fit_params)
  File "C:\Users\MH\.conda\envs\py310\lib\site-packages\imblearn_extra\clover\clusterer\_som.py", line 249, in fit
    self.algorithm_.train(data=X_scaled, **fit_params)
  File "C:\Users\MH\.conda\envs\py310\lib\site-packages\minisom.py", line 434, in train
    self.update(data[iteration], self.winner(data[iteration]),
  File "C:\Users\MH\.conda\envs\py310\lib\site-packages\minisom.py", line 340, in update
    eta = self._decay_function(self._learning_rate, t, max_iteration)
TypeError: 'str' object is not callable

### Environment

1、python==3.10.15
2、imbalanced-learn-extra==0.2.4
3、windows11

**Comment by georgedouzas** [comment]
Hi @AkinaMH,

The latest update of MiniSom introduced breaking changes to their API. I have updated the project's dependencies and made a new release. You can install imbalanced-learn-extra latest version 0.2.5.

**Comment by AkinaMH** [comment]
### Describe the bug
After I installed version 0.2.5, Minisom was updated at the same time, but the system says that the Minisom libraries are not recognised, and that Minisom==2.3.3 already exists in my environment.

Here is the result of installing 0.2.5 and Minisom==2.3.3 at the same time.

Installing collected packages: MiniSom, imbalanced-learn-extra
  Attempting uninstall: MiniSom
    Found existing installation: MiniSom 2.3.2
    Uninstalling MiniSom-2.3.2:
      Successfully uninstalled MiniSom-2.3.2
  Attempting uninstall: imbalanced-learn-extra
    Found existing installation: imbalanced-learn-extra 0.2.4
    Uninstalling imbalanced-learn-extra-0.2.4:
      Successfully uninstalled imbalanced-learn-extra-0.2.4
Successfully installed MiniSom-2.3.3 imbalanced-learn-extra-0.2.5

-------------------------------------------------------------------------------------------

If I install Minisom again, it also shows that it already exists, like the following message.

(py310) PS E:\PyCharm\SNNDPC-SMOTE> pip install minisom                           
Looking in indexes: https://pypi.doubanio.com/simple
Requirement already satisfied: minisom in c:\users\mh\.conda\envs\py310\lib\site-packages (2.3.3)


### Actual Results

Traceback (most recent call last):
  File "E:\PyCharm\SNNDPC-SMOTE\Test.py", line 3, in <module>
    from imblearn_extra.clover.over_sampling import GeometricSOMO
  File "C:\Users\MH\.conda\envs\py310\lib\site-packages\imblearn_extra\clover\over_sampling\__init__.py", line 14, in <module>
    from ._gsomo import GeometricSOMO
  File "C:\Users\MH\.conda\envs\py310\lib\site-packages\imblearn_extra\clover\over_sampling\_gsomo.py", line 19, in <module>
    from ..clusterer import SOM
  File "C:\Users\MH\.conda\envs\py310\lib\site-packages\imblearn_extra\clover\clusterer\__init__.py", line 3, in <module>
    from ._som import SOM, extract_topological_neighbors, generate_labels_mapping
  File "C:\Users\MH\.conda\envs\py310\lib\site-packages\imblearn_extra\clover\clusterer\_som.py", line 12, in <module>
    from minisom import MiniSom
ModuleNotFoundError: No module named 'minisom'


### Environment

1、python==3.10.15
2、imbalanced-learn-extra==0.2.5
3、MiniSom==2.3.3
4、windows11

**Comment by georgedouzas** [comment]
You don't need to install MiniSom seperately, just install imbalanced-learn-extra. It seems like you are not activating the environment before using it.

I suggest to do the following:

- Create a new Pythov virtual environment (version 3.10.x or 3.11.x or 3.12.x).
- Activate the above Python virtual environment.
- `pip install imbalanced-learn-extra`

Then check your script again.

**Comment by AkinaMH** [comment]
I have Python==3.10.15 and have activated the environment, I have tried removing the Minisom library and still have the error. If I remove both the Minisom and imbalanced-learn-extra libraries and then reinstall imbalanced-learn-extra, it still installs Minisom automatically!

**Comment by georgedouzas** [comment]
> I have Python==3.10.15 and have activated the environment, I have tried removing the Minisom library and still have the error.

If the shell command  `python -c "import imblearn_extra"` returns an error then you are not using the correct Python environment. Your questions are not related to imbalanced-learn-extra.

> If I remove both the Minisom and imbalanced-learn-extra libraries and then reinstall imbalanced-learn-extra, it still installs Minisom automatically!

`Minisom` is a dependency of `imbalanced-learn-extra`. This is the expected behaviour.

**Comment by AkinaMH** [comment]
python -c ‘import imblearn_extra’ does not return an error.

**Comment by georgedouzas** [comment]
How about the following commands:

- `python -c "from minisom import MiniSom"`
- `python -c "from imblearn_extra.clover.over_sampling import GeometricSOMO"`

**Comment by AkinaMH** [comment]
(py310) PS E:\PyCharm\SNNDPC-SMOTE> python -c "from minisom import MiniSom"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'minisom'

--------------------------------------------------------------------------

(py310) PS E:\PyCharm\SNNDPC-SMOTE> python -c "from imblearn_extra.clover.over_sampling import GeometricSOMO"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\MH\.conda\envs\py310\lib\site-packages\imblearn_extra\clover\over_sampling\__init__.py", line 14, in <module>
    from ._gsomo import GeometricSOMO
  File "C:\Users\MH\.conda\envs\py310\lib\site-packages\imblearn_extra\clover\over_sampling\_gsomo.py", line 19, in <module>
    from ..clusterer import SOM
  File "C:\Users\MH\.conda\envs\py310\lib\site-packages\imblearn_extra\clover\clusterer\__init__.py", line 3, in <module>
    from ._som import SOM, extract_topological_neighbors, generate_labels_mapping
  File "C:\Users\MH\.conda\envs\py310\lib\site-packages\imblearn_extra\clover\clusterer\_som.py", line 12, in <module>
    from minisom import MiniSom
ModuleNotFoundError: No module named 'minisom'

**Comment by georgedouzas** [comment]
What does the shell command `pip show minisom` return?

**Comment by AkinaMH** [comment]
(py310) PS E:\PyCharm\SNNDPC-SMOTE> pip list | grep MiniSom
grep : 无法将“grep”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 12
+ pip list | grep MiniSom
+            ~~~~
    + CategoryInfo          : ObjectNotFound: (grep:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by georgedouzas** [comment]
I updated the previous command to be compatible with Windows.
